-- Supplement :: LIFE — daily branded educational content (2026-07-15,
-- dashboard architecture pass item #4). One row per day, generated by
-- netlify/functions/generate-daily-digest.mts (a Netlify Scheduled
-- Function) and exposed as an RSS feed at /feed (app/feed/route.ts). A
-- native beehiiv "RSS to Email" Automation (configured in the beehiiv
-- dashboard, not in this codebase) polls that feed and sends each new
-- entry to the mailing list automatically — see lib/beehiiv.ts for why
-- this indirection exists instead of calling a beehiiv "send" API
-- directly.
--
-- Public read is intentional: /feed must be reachable, unauthenticated,
-- by beehiiv's RSS poller. Only service-role (the scheduled function)
-- writes to this table — no public insert/update/delete policy.
--
-- Run this once in the Supabase SQL Editor, same as prior migrations.

create table if not exists public.daily_digest_posts (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  body_html text not null,
  topic text,
  published_at timestamptz not null default now()
);

comment on table public.daily_digest_posts is
  'One row per daily branded educational email, generated by the generate-daily-digest scheduled function and served as RSS at /feed for a beehiiv RSS-to-Email Automation to pick up. Public-read, service-role-write only.';
comment on column public.daily_digest_posts.topic is
  'Loose content-rotation tag (e.g. "hydration", "sleep", "cellular-rejuvenation", an ingredient name) — used only to avoid repeating the same topic on consecutive days, not a foreign key.';

create index if not exists daily_digest_posts_published_at_idx
  on public.daily_digest_posts (published_at desc);

alter table public.daily_digest_posts enable row level security;

drop policy if exists "daily_digest_posts_select_all" on public.daily_digest_posts;
create policy "daily_digest_posts_select_all" on public.daily_digest_posts
  for select using (true);

-- Deliberately no insert/update/delete policy for anon/authenticated —
-- only the service-role key (used by the scheduled function) can write,
-- bypassing RLS entirely, same pattern as notification_log.
